### PR TITLE
#161471006 Improve code maintainability

### PR DESCRIPTION
**Pull request by kevinbett**
## Description (what problem you're fixing)

  - The current code maintainability is poor and there exists test files with large codebases that are not closely related

## Fix (what you did to fix it)

  - Broke down large test files into smaller related modules. 
  - Updated Codeclimate `similar-code mass threshold` to 50

## How to test (describe how to test your PR)

- Clone the repository, install docker, run `make test` within the repository.
- Trigger a build on CircleCI.
- An improvement on code maintainability should be noted on code-climate.

### CODE REVIEW

**Comment by mutoromike** [comment]
Update your branch, and we'll be set.

**Comment by kevinbett** [comment]
@mutoromike I have updated my branch to reflect @frankip 's changes. Should be fine now.

**Comment by kevinbett** [comment]
> Update your branch, and we'll be set.

@mutoromike I have updated my branch to reflect @frankip 's changes. Should be fine now.

**Review by frankip — APPROVED** [review]
LGTM

**Review by mutoromike — APPROVED** [review]
LGTM

**Review by georgreen — APPROVED** [review]
LGTM 😎

**Pull request merged**
