### PR TITLE
#156729671 Restructure repo for docker integration 

### PR DESCRIPTION
**Pull request by FlevianK**
## Resolves #<issue number>
[#156729671](https://www.pivotaltracker.com/n/projects/2162441)

## Description (what problem you're fixing)

  - The project is not using Docker, therefore, the folder structure does not support the addition of docker and scripts.

## Fix (what you did to fix it)

  - Put all application files to a new folder at the root called src
  - Add docker folder that contains all files for docker at any level
 - Add Makefile that holds all commands for running the application on the CMD.

## How to test (describe how to test your PR)

  - The folder structure should look this:
```
├── .circleci
├── .github
├── designs
├── docker
│   ├── dev
│   ├── release
│   └── test
├── scripts
└── src -> project source code
├── .gitignore
├── Makefile
├── README.md
    
```

### CODE REVIEW

**Comment by LarryWachira** [comment]
Squash your commits into one atomic one @FlevianK . Also, speak to the person that setup coveralls to find out where its directory should be placed within the new structure.

**Comment by WinstonKamau** [comment]
@LarryWachira we've squashed the commits and confirmed there will be no effects on the coveralls badge.

**Comment by LarryWachira** [comment]
LGTM.

**Comment by georgreen** [comment]
@FlevianK @WinstonKamau Merge conflicts

**Comment by FlevianK** [comment]
@georgreen This conflict can be solved by the people working on those files. Us (dev-ops team) didn't touch any application files. From observation, there are some changes that were made on develop branch after us pulling the develop branch which are now resulting to conflicts because our work is behind develop with one commit. The right person to solve this conflict is the one who made changes on those files.

**Comment by georgreen** [comment]
@FlevianK cool, then rebase your work if that's the case.

**Pull request merged**
