### PR TITLE
Update setup instructions

### PR DESCRIPTION
**Pull request by rnjane**
## Description (what problem you're fixing)
  - Incomplete setup instruction, wrong database environment variable.

## Fix (what you did to fix it)
  - Update readme with instructions to seed database.
  - Update the database environment variable with the correct one.

### CODE REVIEW

**Comment by georgreen** [comment]
You are working on develop, please switch to a feature/chore/bug branch, push to that and update your PR.

**Comment by LarryWachira** [comment]
@rnjane Are you working on a fork of the project?

**Comment by LarryWachira** [comment]
LGTM.

**Comment by LarryWachira** [comment]
@georgreen Should I proceed with the merge?

**Pull request merged**
